### ISSUE TITLE
Dockerized Postgres instead of Heroku

### ISSUE THREAD

**Issue by hazartilirot** [harblaith7/GraphQL-Course-Udemy#2]
Well, I wonder why most authors complain about how complicating it gets when it comes to set a project up. That's why a docker is invented! There is no need to explain how to set up a Postgres on various OS - just provide a d**ocker-compose.yml** file! 
That's it. 

Any one starting a project just simply executes `docker-compose up` 🚀

For those of you who prefer Docker to Heroku, here's a docker-compose.yml

```
version: '3.9'

services:

  db:
    image: postgres:14.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog-app

volumes: 
     pgdata:
```
Here's a `postgresql://postgres:root@localhost:2345/blog-app`

Mind a port! I've just changed to 2345 since I've got a local instance of Postgres on 5432.

In case you want to enter to a container
`docker exec -it <hash> psql --username=postgres`

a self-explanatory command
`docker-compose down`

A bunch of other command, please execute if you know what they mean. If you don't read RTFM.

`docker ps rm -f $(docker ps ls -q)`

`docker container prune`

`docker volume rm $(docker volume ls -q)`

`docker image rm $(docker image ls -q)`
